In [2]:
from array import array

vals = array('i', [1, 64, 4, 6, 7])

for i in vals:
    print(i)

2
1
64
4
6
7


In [6]:
import numpy

arr = [99, 1, 2, 3, 4, 5]
numpy.sort(arr)
print(arr)

[5, 4, 3, 2, 1, 99]


In [9]:


from numpy import concatenate


arr = [1, 2, 3, 4, 5]
arr2 = [1, 2, 3, 4, 5]


for i in range(len(arr)):
    arr[i] += 5

print(arr)
print("-----------------")
# numpy array
a = array([1, 2, 3, 4, 5])

a += 5
print(sum(a))
print("-----------------")

# concat

print(concatenate([arr, arr2]))
print("-----------------")

# shallow copy; although the address are different if the value of the copy changes the copy will update.
arr3 = a.view()
print(id(arr3))
print(id(a))


print("-----------------")

# deep copy; same copy values but they no longer share any reference or point at the same address
arr4 = a.copy()
print(id(arr4))
print(id(a))

[6, 7, 8, 9, 10]
-----------------
40
-----------------
[ 6  7  8  9 10  1  2  3  4  5]
-----------------
2039194663696
2039194664176
-----------------
2038685927824
2039194664176


In [13]:
from numpy import matrix


r = array([

    [1, 2, 3],
    [5, 6, 7]
])
m = matrix(r)

print(m)

[[1 2 3]
 [5 6 7]]


In [1]:
# binary search tree

my_list = [-5, -3, -2, 1, 3, 5]
# even number of element in list


def binary_s(arr, t):
    l = 0
    r = len(arr)-1
    while l <= r:
        m = l + ((r - l) // 2)
        if arr[m] == t:
            return True
        elif target < arr[m]:
            r = m - 1
        else:
            l = m + 1
    return False


target = 1
binary_s(my_list, target)

True